[[constraint]]
  name = "github.com/deislabs/porter"
  # version = "v0.17.0-beta.1"
  # TODO: change to proper version above
  source = "github.com/vdice/porter"
  branch = "feat/exec-flag-dash"

[prune]
  non-go = true
  go-tests = true
  unused-packages = true
